[tox]
envlist = py311, lint
no_package = true

[testenv]
deps =
    -r requirements.txt

commands =
    python -m pytest

[testenv:lint]
deps =
    black
    isort
    flake8

commands =
    black --check .
    isort --check-only .
    flake8 .
